spring:
  application:
    name: eureka-server
    
#server:
#  port: 2001
  
eureka:
  server:
    enable-self-preservation: false #开发期间关闭自我保护，因为服务会重复启动
#  instance:
#    hostname: eureka1 #定义euerka名字，，集群时需要用该名字互相注册
#  client:
#    register-with-eureka: false #关闭向eureka注册，集群时需要开启
#    fetch-registry: false #拉取注册表
---
spring:
  profiles: eureka1
server:
  port: 2001
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:2002/eureka
---
spring:
  profiles: eureka2
server:
  port: 2002
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka